DEEPSORT:
  REID_CKPT: "deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7"
  MAX_DIST: 0.2
  MIN_CONFIDENCE: 0.3135
  NMS_MAX_OVERLAP: 0.7
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 600
  N_INIT: 3
  NN_BUDGET: 100
  
